/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Tags = string[];
export type Almanac = Region[];

/**
 * Structure of a Dungeon World story archive
 */
export interface DungeonWorldStory {
    name: string;
    people: (Player | Npc)[];
    story?: Chapter[];
    almanac?: Almanac;
}
export interface Player {
    /**
     * A short code used to link to media
     */
    id?: string;
    player: string;
    name: string;
    class: string;
    level: number;
    story?: string;
}
export interface Npc {
    /**
     * A short code used to link to media
     */
    id?: string;
    name: string;
    tags: Tags;
    location?: string;
    description?: string;
}
export interface Chapter {
    name?: string;
    text: string;
}
export interface Region {
    type: "region";
    name: string;
    tags: Tags;
    description?: string;
    moves?: string[];
    children?: (Area | Steading | Site | Encounter | Treasure | Monster)[];
}
export interface Area {
    type: "area";
    name: string;
    tags: Tags;
    description?: string;
    moves?: string[];
    children?: (Steading | Site | Encounter | Treasure | Monster)[];
}
export interface Steading {
    type: "steading";
    name: string;
    tags: Tags;
    description?: string;
    prosperity?: string;
    population?: string;
    defenses?: string;
    moves?: string[];
    children?: (Site | Encounter)[];
}
export interface Site {
    type: "site";
    name: string;
    tags: Tags;
    description?: string;
    moves?: string[];
    children?: (Encounter | Treasure | Monster)[];
}
export interface Encounter {
    type: "encounter";
    name: string;
    tags: Tags;
    description?: string;
    moves?: string[];
}
export interface Treasure {
    type: "treasure";
    name: string;
    tags: Tags;
    description?: string;
    weight?: number;
    value?: number;
    moves?: string[];
}
export interface Monster {
    type: "monster";
    name: string;
    description?: string;
    tags: Tags;
    damage?: string;
    hp?: number;
    armor?: number;
    instincts?: string[];
    moves?: string[];
}
